name: academia_mma
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2  # ✅ Correcto para actualización

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0
  intl: ^0.20.2
  font_awesome_flutter: ^10.7.0
  pdf: 3.11.3
  printing: ^5.12.0 
  http: ^1.2.2
  image_picker: ^1.1.2
  image: 4.3.0
  excel: ^3.0.0
  path_provider: ^2.1.1
  open_file: ^3.3.3
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  awesome_notifications: ^0.10.1
  timezone: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

# ⬇️⬇️⬇️ CONFIGURACIÓN CORREGIDA DEL ICONO ⬇️⬇️⬇️
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"  # Usa tu logo como icono principal
  adaptive_icon_foreground: "assets/logo.jpg"  # Icono para Android moderno
  adaptive_icon_background: "#FFFFFF"  # Fondo blanco
  min_sdk_android: 21  # Android 5.0+
# ⬆️⬆️⬆️ FIN DE LA CONFIGURACIÓN ⬆️⬆️⬆️

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg 
    - assets/img1.jpg
    - assets/img2.jpg
    - assets/img3.jpg
    - assets/icon.jpg  # ⬅️ Agrega esta línea si existe