// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLW6CN6CvF-mAAC66ZG8a3evDeRcN3GYc',
    appId: '1:44868715419:web:2b980b9284cee7edce973e',
    messagingSenderId: '44868715419',
    projectId: 'academia-mma',
    authDomain: 'academia-mma.firebaseapp.com',
    storageBucket: 'academia-mma.firebasestorage.app',
    measurementId: 'G-EGC92SJ6CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOswHcfMkGZqQd8iF73jae4keAtEt6QfQ',
    appId: '1:44868715419:android:fe9e1293867cb1e3ce973e',
    messagingSenderId: '44868715419',
    projectId: 'academia-mma',
    storageBucket: 'academia-mma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_-p2zJ3sNxn6schF_09Wyqv2kdT70HxI',
    appId: '1:44868715419:ios:8e0dcab3b71cf0acce973e',
    messagingSenderId: '44868715419',
    projectId: 'academia-mma',
    storageBucket: 'academia-mma.firebasestorage.app',
    iosBundleId: 'com.example.academiaMma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_-p2zJ3sNxn6schF_09Wyqv2kdT70HxI',
    appId: '1:44868715419:ios:8e0dcab3b71cf0acce973e',
    messagingSenderId: '44868715419',
    projectId: 'academia-mma',
    storageBucket: 'academia-mma.firebasestorage.app',
    iosBundleId: 'com.example.academiaMma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLW6CN6CvF-mAAC66ZG8a3evDeRcN3GYc',
    appId: '1:44868715419:web:337fbe9dbc8d1636ce973e',
    messagingSenderId: '44868715419',
    projectId: 'academia-mma',
    authDomain: 'academia-mma.firebaseapp.com',
    storageBucket: 'academia-mma.firebasestorage.app',
    measurementId: 'G-X7D5CNP8JK',
  );

}